### ISSUE TITLE
Error: TORRENT_READ_FAIL

### ISSUE THREAD

**Issue by evman** [ckcr4lyf/qbit-race#29]
Im running on a shared seedbox, I've tried running qbit-race with Node JS v17.5.0 & v16.13.2 and the error is still persisting.

This is the error I'm getting directly from autodl-irssi:

```
[2022-02-15T03:59:09.819Z] ERROR: Failed to read/parse torrent from file
/media/61eb/avs24/scripts/qbit-race/build/add_torrent.js:35
        throw new Error("TORRENT_READ_FAIL");
              ^

Error: TORRENT_READ_FAIL
    at module.exports (/media/61eb/avs24/scripts/qbit-race/build/add_torrent.js:35:15)
    at Object.<anonymous> (/media/61eb/avs24/scripts/qbit-race/bin/autodl_feed.js:25:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

The error from the qbit-race log file is just this:

`[2022-02-15T03:59:09.819Z] ERROR: Failed to read/parse torrent from file`

Any help would be appreciated.  Thank you!

**Comment by ckcr4lyf** [comment]
Issue resolved offline, was due to incorrect arguments being supplied after breaking change on master. 

Although documentation has been updated, older users may not realize, this error should be refactored to hint users towards the arguments problem. 

Will add such a warning statement to go with the error (perhaps if first argument is a hash / 40 characters AND reading file fails).
